apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ project_slug }}-staging
namePrefix: staging-

resources:
  - ../../base
  - namespace.yaml

commonLabels:
  environment: staging

# Point at your registry / pin a tag here.
images:
  - name: {{ project_slug }}-backend
    newTag: staging
  - name: {{ project_slug }}-frontend
    newTag: staging
