#!/usr/bin/env node
// Scheduled Agent — a dependency-free "cloud session" drop.
//
// Reads a prompt, asks Claude, and opens a GitHub issue with the result. No
// `npm install`: it uses Node 20's built-in global `fetch`. It runs in GitHub
// Actions where ANTHROPIC_API_KEY, GITHUB_TOKEN and GITHUB_REPOSITORY are already
// present (see .github/workflows/scheduled-agent.yml).
//
// Customize it by editing `.github/agent/prompt.md` (the agent's instructions)
// and ISSUE_TITLE below. The default prompt just asks for a short digest of the
// repo's recent activity so the workflow is useful out of the box.

import { readFile } from "node:fs/promises";

const {
  ANTHROPIC_API_KEY,
  GITHUB_TOKEN,
  GITHUB_REPOSITORY,
  MODEL = "{{ claude_model }}",
  AGENT_PROMPT_FILE = ".github/agent/prompt.md",
} = process.env;

function requireEnv(name, value) {
  if (!value) {
    console.error(`✗ ${name} is required (set it as a repo secret / it is provided by Actions).`);
    process.exit(1);
  }
}
requireEnv("ANTHROPIC_API_KEY", ANTHROPIC_API_KEY);
requireEnv("GITHUB_TOKEN", GITHUB_TOKEN);
requireEnv("GITHUB_REPOSITORY", GITHUB_REPOSITORY);

const FALLBACK_PROMPT =
  "You are the {{ project_name }} scheduled agent. Summarize what a maintainer " +
  "should look at this week in one short, skimmable GitHub issue body (markdown). " +
  "Keep it under ~200 words; be concrete; do not invent facts.";

async function loadPrompt() {
  try {
    const text = (await readFile(AGENT_PROMPT_FILE, "utf8")).trim();
    if (text) return text;
  } catch {
    /* no prompt file — fall back */
  }
  return FALLBACK_PROMPT;
}

async function askClaude(prompt) {
  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-api-key": ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: MODEL,
      max_tokens: 2048,
      messages: [{ role: "user", content: prompt }],
    }),
  });
  if (!res.ok) throw new Error(`Anthropic API ${res.status}: ${await res.text()}`);
  const data = await res.json();
  return (data.content || [])
    .filter((b) => b.type === "text")
    .map((b) => b.text)
    .join("\n")
    .trim();
}

async function openIssue(title, body) {
  const res = await fetch(`https://api.github.com/repos/${GITHUB_REPOSITORY}/issues`, {
    method: "POST",
    headers: {
      authorization: `Bearer ${GITHUB_TOKEN}`,
      accept: "application/vnd.github+json",
      "content-type": "application/json",
      "user-agent": "{{ project_slug }}-scheduled-agent",
    },
    body: JSON.stringify({ title, body }),
  });
  if (!res.ok) throw new Error(`GitHub API ${res.status}: ${await res.text()}`);
  return (await res.json()).html_url;
}

const today = new Date().toISOString().slice(0, 10);
const ISSUE_TITLE = `{{ project_name }} agent drop — ${today}`;

const answer = await askClaude(await loadPrompt());
if (!answer) {
  console.error("✗ Empty response from the model; not opening an issue.");
  process.exit(1);
}
const url = await openIssue(
  ISSUE_TITLE,
  `${answer}\n\n---\n_Generated by the \`Scheduled Agent\` workflow (model: ${MODEL})._`,
);
console.log(`✓ Opened ${url}`);
